name: Auto-formatter
run-name: Auto-formatter is formatting code
on:
  push:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./scripts
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: 
          sudo apt-get update
      - run:
          sudo apt-get install clang-format
      - name: Running scripts
        run: bash standardizeFormat.sh
          

