name: Auto-doc
run-name: Auto-doc is formatting and documenting code
on:
  push:
    branches:
      - autoDoxygen 
jobs:
  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./scripts
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install clang-format
      - name: Checkout branch 
        run: |
          git checkout autoDoxygen
          git status
      - name: Run formatting script
        run: 
          bash standardizeFormat.sh
      - name: Install doxygen 
        run:
          sudo apt-get install doxygen 
      - name: Run doxygen on ascendfsw
        run:
          doxygen fswDoxyfile 
      - name: Push formatting changes to repo   
        run: |
          git config user.name "autoformatter[bot]"
          git config user.email "autoformatter[bot]@users.noreply.github.com"
          git status
          if [ "$(git diff)" = "" ]; then
            echo "No formatting needed"
          else 
            git add .. 
            git commit -m "[bot] - autoformatted code"
            git push
          fi
    

