name: Auto-formatter
run-name: Auto-formatter is formatting code
on:
  push:
    branches:
      - testActions
jobs:
  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./scripts
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: 
          sudo apt-get update
      - run:
          sudo apt-get install clang-format
      - name: Running scripts
        run: 
          bash standardizeFormat.sh
      - name: sync changes to repo  
        run: |
          git remote set-url origin ${{ secrets.ssh }}
          git status
          git add .
          git commit -m "Autoformatting code"
          git fetch origin testActions
          git push origin HEAD:testActions 
    
          

