name: Auto-formatter
run-name: Auto-formatter is formatting code
on:
  push:
    branches:
      - testActions
jobs:
  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./scripts
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install clang-format
      - name: Run formatting script
        run: 
          bash standardizeFormat.sh
      - name: Push formatting changes to repo   
        run: |
          git config user.name "autoformatter[bot]"
          git config user.email "autoformatter[bot]@users.noreply.github.com"
          git checkout testActions
          git add .
          git commit -m "generated"
          git push
    
          

